"""empty message

Revision ID: 198a39ef858e
Revises: 9f955d24ff4b
Create Date: 2025-09-29 19:10:02.762197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198a39ef858e'
down_revision = '9f955d24ff4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
